# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseGui.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(350, 212)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main.sizePolicy().hasHeightForWidth())
        Main.setSizePolicy(sizePolicy)
        Main.setMinimumSize(QtCore.QSize(350, 212))
        Main.setMaximumSize(QtCore.QSize(350, 212))
        Main.setBaseSize(QtCore.QSize(350, 212))
        font = QtGui.QFont()
        font.setFamily("Cantarell")
        Main.setFont(font)
        Main.setAcceptDrops(True)
        Main.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 70, 311, 23))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayoutSlider = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayoutSlider.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutSlider.setObjectName("verticalLayoutSlider")
        self.TrackSlider = QtWidgets.QSlider(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TrackSlider.sizePolicy().hasHeightForWidth())
        self.TrackSlider.setSizePolicy(sizePolicy)
        self.TrackSlider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.TrackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TrackSlider.setObjectName("TrackSlider")
        self.verticalLayoutSlider.addWidget(self.TrackSlider)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 331, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutTrackTime = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutTrackTime.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutTrackTime.setObjectName("horizontalLayoutTrackTime")
        self.TrackElapsedText = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.TrackElapsedText.setObjectName("TrackElapsedText")
        self.horizontalLayoutTrackTime.addWidget(self.TrackElapsedText)
        self.TrackLengthText = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.TrackLengthText.setAlignment(QtCore.Qt.AlignCenter)
        self.TrackLengthText.setObjectName("TrackLengthText")
        self.horizontalLayoutTrackTime.addWidget(self.TrackLengthText)
        self.TrackLeftText = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.TrackLeftText.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TrackLeftText.setAutoFillBackground(False)
        self.TrackLeftText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TrackLeftText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TrackLeftText.setObjectName("TrackLeftText")
        self.horizontalLayoutTrackTime.addWidget(self.TrackLeftText)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 331, 42))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayoutTrackButtons = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayoutTrackButtons.setSpacing(0)
        self.horizontalLayoutTrackButtons.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutTrackButtons.setObjectName("horizontalLayoutTrackButtons")
        self.previousButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setMinimumSize(QtCore.QSize(40, 40))
        self.previousButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.previousButton.setFont(font)
        self.previousButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon)
        self.previousButton.setIconSize(QtCore.QSize(40, 40))
        self.previousButton.setFlat(False)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayoutTrackButtons.addWidget(self.previousButton)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(40, 40))
        self.stopButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setAutoFillBackground(False)
        self.stopButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon1)
        self.stopButton.setIconSize(QtCore.QSize(40, 40))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayoutTrackButtons.addWidget(self.stopButton)
        self.playpauseButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playpauseButton.sizePolicy().hasHeightForWidth())
        self.playpauseButton.setSizePolicy(sizePolicy)
        self.playpauseButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playpauseButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.playpauseButton.setFont(font)
        self.playpauseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playpauseButton.setIcon(icon2)
        self.playpauseButton.setIconSize(QtCore.QSize(40, 40))
        self.playpauseButton.setFlat(False)
        self.playpauseButton.setObjectName("playpauseButton")
        self.horizontalLayoutTrackButtons.addWidget(self.playpauseButton)
        self.nextButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMinimumSize(QtCore.QSize(40, 40))
        self.nextButton.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nextButton.setFont(font)
        self.nextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon3)
        self.nextButton.setIconSize(QtCore.QSize(40, 40))
        self.nextButton.setFlat(False)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayoutTrackButtons.addWidget(self.nextButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(9, 5, 331, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TrackInformationText = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.TrackInformationText.setTextFormat(QtCore.Qt.RichText)
        self.TrackInformationText.setAlignment(QtCore.Qt.AlignCenter)
        self.TrackInformationText.setObjectName("TrackInformationText")
        self.horizontalLayout.addWidget(self.TrackInformationText)
        self.trackList = QtWidgets.QListView(self.centralwidget)
        self.trackList.setEnabled(True)
        self.trackList.setGeometry(QtCore.QRect(10, 170, 331, 181))
        self.trackList.setMouseTracking(True)
        self.trackList.setAcceptDrops(True)
        self.trackList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.trackList.setProperty("showDropIndicator", True)
        self.trackList.setDragEnabled(True)
        self.trackList.setDragDropOverwriteMode(False)
        self.trackList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.trackList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.trackList.setAlternatingRowColors(True)
        self.trackList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.trackList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.trackList.setTextElideMode(QtCore.Qt.ElideLeft)
        self.trackList.setMovement(QtWidgets.QListView.Snap)
        self.trackList.setResizeMode(QtWidgets.QListView.Fixed)
        self.trackList.setViewMode(QtWidgets.QListView.ListMode)
        self.trackList.setObjectName("trackList")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 140, 331, 25))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayoutShowHideQueue = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayoutShowHideQueue.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutShowHideQueue.setObjectName("horizontalLayoutShowHideQueue")
        self.expandCheck = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expandCheck.sizePolicy().hasHeightForWidth())
        self.expandCheck.setSizePolicy(sizePolicy)
        self.expandCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.expandCheck.setObjectName("expandCheck")
        self.horizontalLayoutShowHideQueue.addWidget(self.expandCheck)
        self.videoCheck = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.videoCheck.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoCheck.sizePolicy().hasHeightForWidth())
        self.videoCheck.setSizePolicy(sizePolicy)
        self.videoCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.videoCheck.setObjectName("videoCheck")
        self.horizontalLayoutShowHideQueue.addWidget(self.videoCheck)
        self.recentTracksList = QtWidgets.QListView(self.centralwidget)
        self.recentTracksList.setGeometry(QtCore.QRect(350, 10, 191, 341))
        self.recentTracksList.setMouseTracking(True)
        self.recentTracksList.setAcceptDrops(True)
        self.recentTracksList.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.recentTracksList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.recentTracksList.setTextElideMode(QtCore.Qt.ElideLeft)
        self.recentTracksList.setMovement(QtWidgets.QListView.Static)
        self.recentTracksList.setFlow(QtWidgets.QListView.TopToBottom)
        self.recentTracksList.setViewMode(QtWidgets.QListView.ListMode)
        self.recentTracksList.setModelColumn(0)
        self.recentTracksList.setUniformItemSizes(False)
        self.recentTracksList.setObjectName("recentTracksList")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setAcceptDrops(False)
        self.menubar.setObjectName("menubar")
        self.menuHej = QtWidgets.QMenu(self.menubar)
        self.menuHej.setObjectName("menuHej")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Main)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(Main)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_LiMu = QtWidgets.QAction(Main)
        self.actionAbout_LiMu.setObjectName("actionAbout_LiMu")
        self.actionOpen_Several = QtWidgets.QAction(Main)
        self.actionOpen_Several.setObjectName("actionOpen_Several")
        self.actionOpen_Directory = QtWidgets.QAction(Main)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.menuHej.addAction(self.actionOpen)
        self.menuHej.addAction(self.actionOpen_Several)
        self.menuHej.addAction(self.actionOpen_Directory)
        self.menuHej.addSeparator()
        self.menuHej.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_LiMu)
        self.menubar.addAction(self.menuHej.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "LiMu"))
        self.TrackElapsedText.setText(_translate("Main", "Elapsed"))
        self.TrackLengthText.setText(_translate("Main", "Length"))
        self.TrackLeftText.setText(_translate("Main", "Left"))
        self.previousButton.setShortcut(_translate("Main", "Ctrl+S"))
        self.stopButton.setShortcut(_translate("Main", "Media Play"))
        self.playpauseButton.setShortcut(_translate("Main", "Ctrl+S"))
        self.nextButton.setShortcut(_translate("Main", "Ctrl+S"))
        self.TrackInformationText.setText(_translate("Main", "No Track Playing"))
        self.expandCheck.setText(_translate("Main", "Expand"))
        self.videoCheck.setText(_translate("Main", "Video"))
        self.menuHej.setTitle(_translate("Main", "File"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.actionOpen.setText(_translate("Main", "Play Track"))
        self.actionQuit.setText(_translate("Main", "Quit"))
        self.actionAbout_LiMu.setText(_translate("Main", "About LiMu"))
        self.actionOpen_Several.setText(_translate("Main", "Add Track(s)"))
        self.actionOpen_Directory.setText(_translate("Main", "Add Folder"))

